<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-7KH0P1KU" failures="3" tests="3" name="Test" time="22.154" errors="0" timestamp="2025-07-12T23:39:38 IST">
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="6.952">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="6.179">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
  <testcase classname="veer.selenium.selenium.BaseT" name="ARegistrUser" time="7.516">
    <failure type="java.lang.AssertionError" message="This username already exists. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This username already exists. expected [true] but found [false]
at veer.selenium.selenium.POM.Registartion.register(Registartion.java:87)
at veer.selenium.selenium.BaseT.ARegistrUser(BaseT.java:46)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- ARegistrUser -->
</testsuite> <!-- Test -->
